{% set name = "grep-ast" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grep_ast-{{ version }}.tar.gz
  sha256: 620a242a4493e6721338d1c9a6c234ae651f8774f4924a6dcf90f6865d4b2ee3

build:
  entry_points:
    - grep-ast=grep_ast.main:main
    - gast=grep_ast.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - tree-sitter-language-pack
    - python >={{ python_min }}
    - tree_sitter_languages >=1.8.0
    - pathspec

test:
  imports:
    - grep_ast
  commands:
    - pip check
    - grep-ast --help
    - gast --help
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/paul-gauthier/grep-ast
  summary: A tool to grep through the AST of a source file
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - MementoRC
    - jan-janssen
